#!/usr/bin/env bash
# Bash script to install and configure a load
# balancer using haproxy

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y update

sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 89857-web-01 54.236.41.37:80 check\n\tserver 89857-web-02 100.25.19.6:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
